# Generated by Django 5.1 on 2024-09-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloArticulos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen del articulo', null=True, upload_to='articulos/'),
        ),
    ]
